language: node_js
sudo: false
cache: yarn
node_js: 13
git:
  depth: 2
script:
  - yarn lint --quiet
  - yarn test
  - yarn build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  on:
    tags: true
    branch: master
  github_token:
    secure: btVLFpji0R3IRpi2bmvrGLiravKwzGHyULleSJfKQLvAgmxwLmGmNQhprJPL/jHrDd8DsihffPGNi3M4UlRQ+nRvC1Quaes6TdhaJ+iYB2vEFW+Vjko7XMlXCAn6KE1ly6bd1QoggU73erpyilmsV3GwgEz+Xf3hUVqM9MkzOf9aMuhJdw0x+zU6U2aM3mstmtwKkCjnUkkVzLAJcuLuxFdIlYAo6AYi+f4nZXm09MjNvY4R5kk76r5zhVQbBFcalqILiXubbJH3mKsoRN88sTR9sGmnFK7vCCJoj9OYOZ0H4l62RX+hUDD77VKapGxS5NJ6BUhjalWkNZ6DNT/pItb8KSWaQvboZhOf+jJyMfPEoqkkHZGEbGKhqO7uTjzB0CYQKPmcF0sZJc0tr7furF1ZSNTbS6paJUmHsLD2dH1JoM+wkQZrwvjjprDF/ksqe5k+t5BudScTjureyEGZD5Mle5Y7cS+VdFEIwNwdJeZ67+PACvg2PbpFuMcs65p0z1rLnWEPHUDOMP9zqm2KBCpPU9Zja0JVtwSbboRA2GMGCDq6uKgLMfALMhz5YeZRU9VIzOjRSrJfpMgBSx03UMpqDRNMx2ciyYPuoXO5lPiPcEKU9pNeyPsLoAYwARzqdxXz8RZh3q3iRuvrUL7WKhUNVSASt0nRCX9IOWAp/NM=
